var annotated_dup =
[
    [ "Allotjament", "class_allotjament.html", "class_allotjament" ],
    [ "CalculadorRutes", "class_calculador_rutes.html", "class_calculador_rutes" ],
    [ "Client", "class_client.html", "class_client" ],
    [ "Comanda", "class_comanda.html", "class_comanda" ],
    [ "DadesAgencia", "class_dades_agencia.html", "class_dades_agencia" ],
    [ "Desplacament", "class_desplacament.html", "class_desplacament" ],
    [ "Destinacio", "class_destinacio.html", "class_destinacio" ],
    [ "Estacio", "class_estacio.html", "class_estacio" ],
    [ "EstadaAllotjament", "class_estada_allotjament.html", "class_estada_allotjament" ],
    [ "Excepcions", "class_excepcions.html", null ],
    [ "GUI", "class_g_u_i.html", "class_g_u_i" ],
    [ "Horari", "class_horari.html", "class_horari" ],
    [ "ItemRuta", "class_item_ruta.html", "class_item_ruta" ],
    [ "Lloc", "class_lloc.html", "class_lloc" ],
    [ "LlocVisitable", "class_lloc_visitable.html", "class_lloc_visitable" ],
    [ "MitjaTransport", "class_mitja_transport.html", "class_mitja_transport" ],
    [ "Pair", "class_pair.html", "class_pair" ],
    [ "PuntInteres", "class_punt_interes.html", "class_punt_interes" ],
    [ "Ruta", "class_ruta.html", "class_ruta" ],
    [ "TransportDirecte", "class_transport_directe.html", "class_transport_directe" ],
    [ "TransportIndirecte", "class_transport_indirecte.html", "class_transport_indirecte" ],
    [ "TransportPublic", "class_transport_public.html", "class_transport_public" ],
    [ "Visita", "class_visita.html", "class_visita" ]
];